name: unit_test
channels:
  - conda-forge
dependencies:
  - jupyterlab=4.3.5
  - jupyterlab-plotly-extension=1.0.0
  - jupyterlab-spellchecker=0.8.4
  - numpy=2.2.3
  - pandas=2.2.2
  - pip=25.0.1
  - python=3.12
  - pytest=8.3.5
